[2025-09-26 22:35:04,261: INFO: main]: Starting the CNN Classifier application...
[2025-09-26 22:42:15,795: INFO: main]: Starting the CNN Classifier application...
[2025-09-26 22:42:41,277: INFO: main]: Starting the CNN Classifier application...
[2025-09-27 01:47:27,048: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:47:27,057: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:51:11,134: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:51:11,136: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:51:46,794: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:51:46,796: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:51:46,799: INFO: common]: Created directory at: artifacts
[2025-09-27 01:51:46,802: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 01:51:46,804: INFO: 2108146548]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 01:55:47,667: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 01:55:47,670: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 01:55:47,673: INFO: common]: Created directory at: artifacts
[2025-09-27 01:55:47,674: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 01:55:47,678: INFO: 2108146548]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:00:26,990: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:00:26,993: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:00:26,996: INFO: common]: Created directory at: artifacts
[2025-09-27 02:00:26,998: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:00:27,000: INFO: 3513763619]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:01:06,586: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:01:06,589: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:01:06,591: INFO: common]: Created directory at: artifacts
[2025-09-27 02:01:06,594: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:01:06,596: INFO: 2789812827]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:02:18,786: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:02:18,788: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:02:18,791: INFO: common]: Created directory at: artifacts
[2025-09-27 02:02:18,794: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:02:18,795: INFO: 2071522955]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:04:33,205: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:04:33,208: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:04:33,211: INFO: common]: Created directory at: artifacts
[2025-09-27 02:04:33,213: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:04:33,215: INFO: 2071522955]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:04:42,027: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:04:42,030: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:04:42,033: INFO: common]: Created directory at: artifacts
[2025-09-27 02:04:42,035: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:04:42,037: INFO: 3050489163]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:07:27,655: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:07:27,659: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:07:27,661: INFO: common]: Created directory at: artifacts
[2025-09-27 02:07:27,668: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:07:27,671: INFO: 2846847418]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:09:06,002: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:09:06,005: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:09:06,009: INFO: common]: Created directory at: artifacts
[2025-09-27 02:09:06,013: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:09:06,015: INFO: 3097298046]: Downloading file from : https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link to : artifacts\data_injection\data.zip
[2025-09-27 02:11:46,486: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 02:11:46,489: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 02:11:46,492: INFO: common]: Created directory at: artifacts
[2025-09-27 02:11:46,496: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 02:11:46,499: INFO: 2746166564]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:19:37,993: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:19:38,001: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:19:38,004: INFO: common]: Created directory at: artifacts
[2025-09-27 23:19:38,006: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:19:38,010: INFO: 2746166564]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:23:08,847: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:23:08,850: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:23:08,853: INFO: common]: Created directory at: artifacts
[2025-09-27 23:23:08,855: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:23:08,858: INFO: 2746166564]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:26:11,655: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:26:11,658: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:26:11,660: INFO: common]: Created directory at: artifacts
[2025-09-27 23:26:11,663: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:26:11,665: INFO: 2069769915]: Downloading file from :[https://drive.google.com/file/d/1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=drive_link] to :[artifacts\data_injection\data.zip]
[2025-09-27 23:27:08,490: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:27:08,492: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:27:08,495: INFO: common]: Created directory at: artifacts
[2025-09-27 23:27:08,499: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:27:08,504: INFO: 2069769915]: File already exists of size :[~ 104 KB]
[2025-09-27 23:27:13,266: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:27:13,269: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:27:13,271: INFO: common]: Created directory at: artifacts
[2025-09-27 23:27:13,273: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:27:13,276: INFO: 2069769915]: File already exists of size :[~ 104 KB]
[2025-09-27 23:27:24,057: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:27:24,060: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:27:24,062: INFO: common]: Created directory at: artifacts
[2025-09-27 23:27:24,064: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:27:24,067: INFO: 2069769915]: File already exists of size :[~ 104 KB]
[2025-09-27 23:37:08,051: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:37:08,053: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:37:08,056: INFO: common]: Created directory at: artifacts
[2025-09-27 23:37:08,058: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:37:08,061: INFO: 3970809810]: File already exists of size: [~ 104 KB]
[2025-09-27 23:41:39,985: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-27 23:41:39,988: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-27 23:41:39,992: INFO: common]: Created directory at: artifacts
[2025-09-27 23:41:40,095: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-27 23:41:40,099: INFO: 3970809810]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-09-27 23:46:47,744: INFO: 3970809810]: Extracted zip file to: artifacts\data_injection
[2025-09-28 12:48:18,512: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 12:48:18,540: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 12:48:18,543: INFO: common]: Created directory at: artifacts
[2025-09-28 12:48:18,566: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 12:48:18,568: INFO: 113322524]: Downloading file from: https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=share_link
[2025-09-28 12:54:35,159: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 12:54:35,163: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 12:54:35,165: INFO: common]: Created directory at: artifacts
[2025-09-28 12:54:35,168: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 12:54:35,171: INFO: 2813457312]: Downloading file from: https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1/view?usp=share_link
[2025-09-28 12:56:32,672: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 12:56:32,674: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 12:56:32,677: INFO: common]: Created directory at: artifacts
[2025-09-28 12:56:32,680: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 12:56:32,684: INFO: 1482965000]: Downloading file from: https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1
[2025-09-28 13:01:49,362: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 13:01:49,365: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 13:01:49,368: INFO: common]: Created directory at: artifacts
[2025-09-28 13:01:49,370: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 13:01:49,373: INFO: 3970809810]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-09-28 13:08:27,482: INFO: 3970809810]: Extracted zip file to: artifacts\data_injection
[2025-09-28 16:06:16,381: ERROR: main]: name 'STAGE_NAME' is not defined
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 6, in <module>
    logger.info(f">>>>>>> Stage {STAGE_NAME} started <<<<<<<<")
NameError: name 'STAGE_NAME' is not defined
[2025-09-28 16:07:49,488: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-09-28 16:07:49,593: ERROR: main]: __init__() missing 1 required positional argument: 'config'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 9, in <module>
    obj = DataIngestionTrainingPipeline()
TypeError: __init__() missing 1 required positional argument: 'config'
[2025-09-28 16:09:30,883: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-09-28 16:09:30,883: ERROR: main]: __init__() missing 4 required positional arguments: 'root_dir', 'source_URL', 'local_data_file', and 'unzip_dir'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 10, in <module>
    obj = DataIngestionTrainingPipeline(DataInjectionConfig())
TypeError: __init__() missing 4 required positional arguments: 'root_dir', 'source_URL', 'local_data_file', and 'unzip_dir'
[2025-09-28 17:27:21,910: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-09-28 17:27:21,914: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-09-28 17:27:21,916: INFO: common]: yaml file: params.yaml loaded successfully
[2025-09-28 17:27:21,917: INFO: common]: Created directory at: artifacts
[2025-09-28 17:27:21,919: INFO: common]: Created directory at: artifacts/data_injection
[2025-09-28 17:27:21,920: INFO: data_ingestion]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-09-28 17:34:54,186: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-09-28 17:34:54,190: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-01 22:44:23,950: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:44:23,983: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:44:23,987: INFO: common]: Created directory at: artifacts
[2025-10-01 22:44:23,990: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 22:49:14,115: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:49:14,119: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:49:14,121: INFO: common]: Created directory at: artifacts
[2025-10-01 22:49:14,123: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 22:55:16,719: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:55:16,725: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:55:16,731: INFO: common]: Created directory at: artifacts
[2025-10-01 22:55:16,734: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 22:59:12,424: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 22:59:12,430: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 22:59:12,434: INFO: common]: Created directory at: artifacts
[2025-10-01 22:59:12,438: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:00:07,076: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:00:07,080: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:00:07,083: INFO: common]: Created directory at: artifacts
[2025-10-01 23:00:07,087: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:00:36,848: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:00:36,852: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:00:36,855: INFO: common]: Created directory at: artifacts
[2025-10-01 23:00:36,857: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:01:04,472: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-01 23:12:41,795: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-01 23:12:41,797: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:12:41,799: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:12:41,800: INFO: common]: Created directory at: artifacts
[2025-10-01 23:12:41,801: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-01 23:12:41,801: INFO: data_ingestion]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-10-01 23:17:04,026: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-01 23:17:04,033: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-01 23:17:04,034: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-01 23:17:04,035: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:17:04,037: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:17:04,037: INFO: common]: Created directory at: artifacts
[2025-10-01 23:17:04,039: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:17:04,039: ERROR: main]: 'PrepareBaseModelConfig' object has no attribute 'params_include_top'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 18, in main
    prepare_base_model.get_base_model()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\components\prepare_base_model.py", line 15, in get_base_model
    include_top=self.config.params_include_top,
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'params_include_top'
[2025-10-01 23:23:48,143: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-01 23:23:48,145: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:23:48,147: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:23:48,148: INFO: common]: Created directory at: artifacts
[2025-10-01 23:23:48,148: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-01 23:23:48,149: INFO: data_ingestion]: Downloading file from: [https://drive.google.com/uc?id=1japQFug4eo3bz9mKibbk-aR4YJVhU4H1] to: [artifacts\data_injection\data.zip]
[2025-10-01 23:29:33,668: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-01 23:29:33,672: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-01 23:29:33,672: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-01 23:29:33,674: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-01 23:29:33,675: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-01 23:29:33,675: INFO: common]: Created directory at: artifacts
[2025-10-01 23:29:33,677: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-01 23:29:33,677: ERROR: main]: __init__() got an unexpected keyword argument 'image_size'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'image_size'
[2025-10-02 00:08:12,435: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:08:12,438: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:08:12,440: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:08:12,441: INFO: common]: Created directory at: artifacts
[2025-10-02 00:08:12,442: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:08:12,444: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:09:16,230: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:09:16,233: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:09:16,234: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:09:16,237: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:09:16,238: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:09:16,239: INFO: common]: Created directory at: artifacts
[2025-10-02 00:09:16,239: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:09:16,240: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:14:23,728: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:14:23,731: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:14:23,733: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:14:23,735: INFO: common]: Created directory at: artifacts
[2025-10-02 00:14:23,735: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:14:23,737: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:15:28,559: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:15:28,565: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:15:28,566: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:15:28,569: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:15:28,574: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:15:28,575: INFO: common]: Created directory at: artifacts
[2025-10-02 00:15:28,575: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:15:28,576: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:20:02,655: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:20:02,657: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:20:02,659: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:20:02,660: INFO: common]: Created directory at: artifacts
[2025-10-02 00:20:02,662: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:20:02,662: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:21:19,361: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:21:19,439: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:21:19,439: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:21:19,444: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:21:19,447: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:21:19,448: INFO: common]: Created directory at: artifacts
[2025-10-02 00:21:19,449: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:21:19,449: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:33:19,072: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:33:19,074: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:33:19,076: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:33:19,076: INFO: common]: Created directory at: artifacts
[2025-10-02 00:33:19,077: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:33:19,078: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:34:22,862: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:34:22,954: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:34:22,954: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:34:22,956: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:34:22,957: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:34:22,958: INFO: common]: Created directory at: artifacts
[2025-10-02 00:34:22,959: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:34:22,959: ERROR: main]: PrepareBaseModelConfig() takes no arguments
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: PrepareBaseModelConfig() takes no arguments
[2025-10-02 00:37:36,884: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:37:36,886: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:37:36,887: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:37:36,888: INFO: common]: Created directory at: artifacts
[2025-10-02 00:37:36,888: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:37:36,888: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:38:41,538: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:38:41,543: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:38:41,543: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:38:41,546: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:38:41,548: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:38:41,550: INFO: common]: Created directory at: artifacts
[2025-10-02 00:38:41,550: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:38:41,550: ERROR: main]: __init__() got an unexpected keyword argument 'image_size'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 21, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 30, in get_prepare_base_model_config
    prepare_base_model_config = PrepareBaseModelConfig(
TypeError: __init__() got an unexpected keyword argument 'image_size'
[2025-10-02 00:43:06,766: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 00:43:06,768: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:43:06,772: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:43:06,774: INFO: common]: Created directory at: artifacts
[2025-10-02 00:43:06,776: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 00:43:06,777: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 00:44:11,300: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 00:44:11,322: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 00:44:11,322: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 00:44:11,406: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 00:44:11,408: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 00:44:11,410: INFO: common]: Created directory at: artifacts
[2025-10-02 00:44:11,410: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 00:44:12,017: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 00:44:13,767: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 02:29:17,150: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:29:17,155: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:29:17,158: INFO: common]: Created directory at: artifacts
[2025-10-02 02:31:09,546: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:31:09,552: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:31:09,554: INFO: common]: Created directory at: artifacts
[2025-10-02 02:31:09,558: INFO: common]: Created directory at: artifacts\training
[2025-10-02 02:47:56,655: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 02:47:56,658: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:47:56,659: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:47:56,660: INFO: common]: Created directory at: artifacts
[2025-10-02 02:47:56,660: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 02:47:56,660: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 02:48:47,822: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 02:48:47,826: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 02:48:47,826: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 02:48:47,829: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:48:47,831: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:48:47,832: INFO: common]: Created directory at: artifacts
[2025-10-02 02:48:47,833: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 02:48:48,557: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 02:48:51,039: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 02:48:51,040: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-02 02:48:51,042: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:48:51,045: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:48:51,046: INFO: common]: Created directory at: artifacts
[2025-10-02 02:48:51,049: ERROR: main]: "'ConfigBox' object has no attribute 'data_ingestion'"
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'data_ingestion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'data_ingestion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'data_ingestion'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'data_ingestion'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 33, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_03_model_training.py", line 13, in main
    training_config = config.get_training_config()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\config\configuration.py", line 46, in get_training_config
    training_data = os.path.join(self.config.data_ingestion.unzip_dir,"CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone")
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'data_ingestion'"
[2025-10-02 02:50:59,335: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 02:50:59,350: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:50:59,353: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:50:59,353: INFO: common]: Created directory at: artifacts
[2025-10-02 02:50:59,354: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 02:50:59,354: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 02:51:50,380: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 02:51:50,384: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 02:51:50,385: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 02:51:50,386: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:51:50,388: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:51:50,389: INFO: common]: Created directory at: artifacts
[2025-10-02 02:51:50,389: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 02:51:51,088: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 02:51:52,650: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 02:51:52,651: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-02 02:51:52,653: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 02:51:52,655: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 02:51:52,656: INFO: common]: Created directory at: artifacts
[2025-10-02 02:51:52,656: INFO: common]: Created directory at: artifacts\training
[2025-10-02 03:36:53,947: INFO: main]: >>>>>>> Stage Training completed <<<<<<<<

x==========x
[2025-10-02 23:02:11,063: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 23:02:11,095: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 23:02:11,097: INFO: common]: Created directory at: artifacts
[2025-10-02 23:27:36,189: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-02 23:27:36,192: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 23:27:36,194: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 23:27:36,195: INFO: common]: Created directory at: artifacts
[2025-10-02 23:27:36,196: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-02 23:27:36,197: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-02 23:28:40,514: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-02 23:28:40,519: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-02 23:28:40,519: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-02 23:28:40,521: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 23:28:40,523: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 23:28:40,523: INFO: common]: Created directory at: artifacts
[2025-10-02 23:28:40,524: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-02 23:28:41,320: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-02 23:28:42,485: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-02 23:28:42,485: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-02 23:28:42,488: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-02 23:28:42,491: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-02 23:28:42,492: INFO: common]: Created directory at: artifacts
[2025-10-02 23:28:42,493: INFO: common]: Created directory at: artifacts\training
[2025-10-03 00:17:08,674: INFO: main]: >>>>>>> Stage Training completed <<<<<<<<

x==========x
[2025-10-03 00:17:08,675: INFO: main]: >>>>>>> Stage Model Evaluation Stage started <<<<<<<<
[2025-10-03 00:17:08,680: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 00:17:08,682: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 00:17:08,684: INFO: common]: Created directory at: artifacts
[2025-10-03 00:28:31,721: INFO: common]: json file saved at: scores.json
[2025-10-03 00:28:34,060: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2025-10-03 00:28:35,119: INFO: builder_impl]: Assets written to: C:\Users\dadhi\AppData\Local\Temp\tmpins0l_kh\model\data\model\assets
[2025-10-03 00:28:55,551: ERROR: main]: No module named 'distutils._modified'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 45, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\components\model_evaluation.py", line 62, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 150, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 192, in _copy_one
    file_util.copy_file(
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-10-03 18:08:21,455: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-03 18:08:21,575: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 18:08:21,609: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 18:08:21,611: INFO: common]: Created directory at: artifacts
[2025-10-03 18:08:21,612: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-03 18:08:21,614: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-03 18:10:09,251: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-03 18:10:09,254: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-03 18:10:09,255: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-03 18:10:09,256: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 18:10:09,258: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 18:10:09,258: INFO: common]: Created directory at: artifacts
[2025-10-03 18:10:09,259: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-03 18:10:09,986: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-03 18:10:10,605: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-03 18:10:10,605: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-03 18:10:10,607: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 18:10:10,609: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 18:10:10,611: INFO: common]: Created directory at: artifacts
[2025-10-03 18:10:10,611: INFO: common]: Created directory at: artifacts\training
[2025-10-03 18:51:44,360: INFO: main]: >>>>>>> Stage Training completed <<<<<<<<

x==========x
[2025-10-03 18:51:44,360: INFO: main]: >>>>>>> Stage Model Evaluation Stage started <<<<<<<<
[2025-10-03 18:51:44,362: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 18:51:44,364: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 18:51:44,365: INFO: common]: Created directory at: artifacts
[2025-10-03 18:59:48,217: INFO: common]: json file saved at: scores.json
[2025-10-03 18:59:50,279: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2025-10-03 18:59:51,075: INFO: builder_impl]: Assets written to: C:\Users\dadhi\AppData\Local\Temp\tmp69jig1bv\model\data\model\assets
[2025-10-03 19:00:05,590: ERROR: main]: No module named 'distutils._modified'
Traceback (most recent call last):
  File "F:\kidney-Disease-Classification_DL\main.py", line 45, in <module>
    obj.main()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\pipeline\stage_04_model_evaluation.py", line 19, in main
    evaluation.log_into_mlflow()
  File "f:\kidney-disease-classification_dl\src\CNNClassifier\components\model_evaluation.py", line 62, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 58, in log_artifacts
    dir_util.copy_tree(src=local_dir, dst=artifact_dir, preserve_mode=0, preserve_times=0)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 150, in copy_tree
    return list(itertools.chain.from_iterable(map(copy_one, names)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\dir_util.py", line 192, in _copy_one
    file_util.copy_file(
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
    from distutils._modified import newer
ModuleNotFoundError: No module named 'distutils._modified'
[2025-10-03 22:04:16,343: INFO: main]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-03 22:04:16,439: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 22:04:16,449: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 22:04:16,450: INFO: common]: Created directory at: artifacts
[2025-10-03 22:04:16,453: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-03 22:04:16,455: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-03 22:06:02,521: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-03 22:06:02,529: INFO: main]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-03 22:06:02,529: INFO: main]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-03 22:06:02,536: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 22:06:02,541: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 22:06:02,542: INFO: common]: Created directory at: artifacts
[2025-10-03 22:06:02,545: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-03 22:06:04,380: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-03 22:06:05,790: INFO: main]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-03 22:06:05,791: INFO: main]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-03 22:06:05,797: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 22:06:05,801: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 22:06:05,802: INFO: common]: Created directory at: artifacts
[2025-10-03 22:06:05,805: INFO: common]: Created directory at: artifacts\training
[2025-10-03 23:03:55,078: INFO: main]: >>>>>>> Stage Training completed <<<<<<<<

x==========x
[2025-10-03 23:03:55,079: INFO: main]: >>>>>>> Stage Model Evaluation Stage started <<<<<<<<
[2025-10-03 23:03:55,083: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-03 23:03:55,087: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-03 23:03:55,089: INFO: common]: Created directory at: artifacts
[2025-10-03 23:15:18,179: INFO: common]: json file saved at: scores.json
[2025-10-03 23:15:20,431: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2025-10-03 23:15:21,529: INFO: builder_impl]: Assets written to: C:\Users\dadhi\AppData\Local\Temp\tmpl6aqzx7n\model\data\model\assets
[2025-10-03 23:15:36,778: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\6f27243ef89b41d49d88d0ab109e52e1\artifacts\model\data
[2025-10-03 23:15:36,785: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\6f27243ef89b41d49d88d0ab109e52e1\artifacts\model\data\model
[2025-10-03 23:15:36,787: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\6f27243ef89b41d49d88d0ab109e52e1\artifacts\model\data\model\assets
[2025-10-03 23:15:36,793: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\6f27243ef89b41d49d88d0ab109e52e1\artifacts\model\data\model\variables
[2025-10-03 23:15:36,944: INFO: main]: >>>>>>> Stage Model Evaluation Stage completed <<<<<<<<

x==========x
[2025-10-04 01:38:30,414: INFO: stage_01_data_ingestion]: >>>>>>> Stage Data Ingestion Stage started <<<<<<<<
[2025-10-04 01:38:30,418: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-04 01:38:30,420: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-04 01:38:30,421: INFO: common]: Created directory at: artifacts
[2025-10-04 01:38:30,422: INFO: common]: Created directory at: artifacts/data_injection
[2025-10-04 01:38:30,423: INFO: data_ingestion]: File already exists of size: [~ 1588634 KB]
[2025-10-04 01:39:46,095: INFO: data_ingestion]: Extracted zip file to: artifacts\data_injection
[2025-10-04 01:39:46,098: INFO: stage_01_data_ingestion]: >>>>>>> Stage Data Ingestion Stage completed <<<<<<<<

x==========x
[2025-10-04 01:45:04,489: INFO: stage_02_prepare_base_model]: >>>>>>> Stage Prepare Base Model Stage started <<<<<<<<
[2025-10-04 01:45:04,513: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-04 01:45:04,518: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-04 01:45:04,519: INFO: common]: Created directory at: artifacts
[2025-10-04 01:45:04,520: INFO: common]: Created directory at: artifacts/prepare_base_model
[2025-10-04 01:45:05,409: WARNING: saving_utils]: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
[2025-10-04 01:45:05,804: INFO: stage_02_prepare_base_model]: >>>>>>> Stage Prepare Base Model Stage completed <<<<<<<<

x==========x
[2025-10-04 01:45:21,900: INFO: stage_03_model_training]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-04 01:45:21,902: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-04 01:45:21,904: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-04 01:45:21,908: INFO: common]: Created directory at: artifacts
[2025-10-04 01:45:21,909: INFO: common]: Created directory at: artifacts\training
[2025-10-04 01:46:14,146: INFO: stage_03_model_training]: >>>>>>> Stage Training started <<<<<<<<
[2025-10-04 01:46:14,147: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-04 01:46:14,150: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-04 01:46:14,151: INFO: common]: Created directory at: artifacts
[2025-10-04 01:46:14,151: INFO: common]: Created directory at: artifacts\training
[2025-10-04 02:42:20,856: INFO: stage_03_model_training]: >>>>>>> Stage Training completed <<<<<<<<

x==========x
[2025-10-04 02:42:39,785: INFO: stage_04_model_evaluation]: >>>>>>> Stage Model Evaluation Stage started <<<<<<<<
[2025-10-04 02:42:39,788: INFO: common]: yaml file: config\config.yaml loaded successfully
[2025-10-04 02:42:39,790: INFO: common]: yaml file: params.yaml loaded successfully
[2025-10-04 02:42:39,790: INFO: common]: Created directory at: artifacts
[2025-10-04 02:50:55,185: INFO: common]: json file saved at: scores.json
[2025-10-04 02:50:56,926: WARNING: save]: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.
[2025-10-04 02:50:57,859: INFO: builder_impl]: Assets written to: C:\Users\dadhi\AppData\Local\Temp\tmpudvya1da\model\data\model\assets
[2025-10-04 02:51:08,004: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\9dfc23b570774a4f9553d4af4b6b50ec\artifacts\model\data
[2025-10-04 02:51:08,008: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\9dfc23b570774a4f9553d4af4b6b50ec\artifacts\model\data\model
[2025-10-04 02:51:08,008: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\9dfc23b570774a4f9553d4af4b6b50ec\artifacts\model\data\model\assets
[2025-10-04 02:51:08,013: INFO: dir_util]: creating F:\kidney-Disease-Classification_DL\mlruns\0\9dfc23b570774a4f9553d4af4b6b50ec\artifacts\model\data\model\variables
[2025-10-04 02:51:08,134: INFO: stage_04_model_evaluation]: >>>>>>> Stage Model Evaluation Stage completed <<<<<<<<

x==========x
[2025-10-04 18:15:04,905: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 18:15:04,905: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 18:15:28,192: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:15:28] "GET / HTTP/1.1" 200 -
[2025-10-04 18:15:43,401: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:15:43] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:16:02,218: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:16:02] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:16:10,999: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:16:10] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:16:24,103: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:16:24] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:16:56,081: WARNING: polymorphic_function]: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E565272430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 18:16:56,092: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:16:56] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:17:09,359: WARNING: polymorphic_function]: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001E5653CF790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 18:17:09,368: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:17:09] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:32:30,592: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 18:32:30,594: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 18:32:46,530: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:32:46] "GET / HTTP/1.1" 200 -
[2025-10-04 18:32:59,686: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:32:59] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:33:13,559: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:33:13] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:33:32,755: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:33:32] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:33:39,052: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:33:39] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:33:46,117: WARNING: polymorphic_function]: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020C4CBF2430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 18:33:46,122: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:33:46] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:33:54,168: WARNING: polymorphic_function]: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020C4CC20790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 18:33:54,175: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:33:54] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:34:05,612: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:34:05] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:34:15,005: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:34:15] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:34:18,433: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:34:18] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:40:06,265: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 18:40:06,266: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 18:40:24,566: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:40:24] "GET / HTTP/1.1" 200 -
[2025-10-04 18:40:36,881: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:40:36] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:40:49,952: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:40:49] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:41:04,432: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:41:04] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:41:13,221: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:41:13] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:41:22,590: WARNING: polymorphic_function]: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000022DA6434430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 18:41:22,597: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:41:22] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:41:34,352: WARNING: polymorphic_function]: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000022DA658E790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 18:41:34,361: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:41:34] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:41:44,199: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:41:44] "POST /predict HTTP/1.1" 200 -
[2025-10-04 18:59:48,973: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 18:59:48,974: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 18:59:54,471: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 18:59:54] "GET / HTTP/1.1" 200 -
[2025-10-04 19:00:04,382: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 35, in predict
    client_app = ClientApp()
  File "F:\kidney-Disease-Classification_DL\app.py", line 16, in __init__
    self.prediction_pipeline = Prediction(self.filename)
TypeError: __init__() takes 1 positional argument but 2 were given
[2025-10-04 19:00:04,407: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:00:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:00:06,628: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 35, in predict
    client_app = ClientApp()
  File "F:\kidney-Disease-Classification_DL\app.py", line 16, in __init__
    self.prediction_pipeline = Prediction(self.filename)
TypeError: __init__() takes 1 positional argument but 2 were given
[2025-10-04 19:00:06,630: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:00:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:00:06,909: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 35, in predict
    client_app = ClientApp()
  File "F:\kidney-Disease-Classification_DL\app.py", line 16, in __init__
    self.prediction_pipeline = Prediction(self.filename)
TypeError: __init__() takes 1 positional argument but 2 were given
[2025-10-04 19:00:06,912: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:00:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:01:26,184: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:01:26,188: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:01:31,034: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:01:31] "GET / HTTP/1.1" 200 -
[2025-10-04 19:01:46,827: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 37, in predict
    pred = client_app.prediction_pipeline.predict()
TypeError: predict() missing 1 required positional argument: 'filename'
[2025-10-04 19:01:46,859: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:01:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:05:10,859: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:05:10,860: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:05:15,739: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:05:15] "GET / HTTP/1.1" 200 -
[2025-10-04 19:05:31,139: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 37, in predict
    pred = client_app.prediction_pipeline.predict()
  File "F:\kidney-Disease-Classification_DL\src\CNNClassifier\pipeline\prediction.py", line 20, in predict
    elif result[0][1] == 1:
IndexError: invalid index to scalar variable.
[2025-10-04 19:05:31,159: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:05:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:07:08,510: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 37, in predict
    pred = client_app.prediction_pipeline.predict()
  File "F:\kidney-Disease-Classification_DL\src\CNNClassifier\pipeline\prediction.py", line 20, in predict
IndexError: invalid index to scalar variable.
[2025-10-04 19:07:08,578: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:07:08] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:07:31,509: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:07:31,510: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:07:37,883: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:07:37] "GET / HTTP/1.1" 200 -
[2025-10-04 19:07:52,086: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 37, in predict
    pred = client_app.prediction_pipeline.predict()
  File "F:\kidney-Disease-Classification_DL\src\CNNClassifier\pipeline\prediction.py", line 18, in predict
    prediction = self.classes[result]
TypeError: only integer scalar arrays can be converted to a scalar index
[2025-10-04 19:07:52,099: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:07:52] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:08:17,174: ERROR: app]: Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\dadhi\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "F:\kidney-Disease-Classification_DL\app.py", line 37, in predict
    pred = client_app.prediction_pipeline.predict()
  File "F:\kidney-Disease-Classification_DL\src\CNNClassifier\pipeline\prediction.py", line 18, in predict
    prediction = self.classes[result[0]]
TypeError: only integer scalar arrays can be converted to a scalar index
[2025-10-04 19:08:17,209: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:08:17] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
[2025-10-04 19:08:47,003: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:08:47,003: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:08:50,315: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:08:50] "GET / HTTP/1.1" 200 -
[2025-10-04 19:09:07,777: INFO: _internal]: 192.168.108.179 - - [04/Oct/2025 19:09:07] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:17:44,261: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:17:44,262: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:17:53,823: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:17:53] "GET / HTTP/1.1" 200 -
[2025-10-04 19:18:06,136: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:18:06] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:18:20,229: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:18:20] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:18:23,080: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:18:23] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:18:30,136: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:18:30] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:19:27,946: WARNING: polymorphic_function]: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021993DEF280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 19:19:27,951: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:19:27] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:19:51,944: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:19:51,945: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:19:56,838: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:19:56] "GET / HTTP/1.1" 200 -
[2025-10-04 19:20:05,820: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:20:05] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:24:06,892: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:24:06,892: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:24:08,557: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:24:08] "GET / HTTP/1.1" 200 -
[2025-10-04 19:24:10,189: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:24:10] "GET / HTTP/1.1" 200 -
[2025-10-04 19:24:18,558: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:24:18] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:32:42,213: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-04 19:32:42,213: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-04 19:32:59,313: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:32:59] "GET / HTTP/1.1" 200 -
[2025-10-04 19:32:59,636: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:32:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2025-10-04 19:33:13,693: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:33:13] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:34:50,160: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:34:50] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:34:59,541: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:34:59] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:35:08,115: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:35:08] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:35:19,123: WARNING: polymorphic_function]: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021A61D52B80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 19:35:19,129: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:35:19] "POST /predict HTTP/1.1" 200 -
[2025-10-04 19:35:27,910: WARNING: polymorphic_function]: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021A61D521F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[2025-10-04 19:35:27,913: INFO: _internal]: 127.0.0.1 - - [04/Oct/2025 19:35:27] "POST /predict HTTP/1.1" 200 -
[2025-10-05 00:54:42,702: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:54:42] "GET / HTTP/1.1" 200 -
[2025-10-05 00:54:54,419: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:54:54] "POST /predict HTTP/1.1" 200 -
[2025-10-05 00:55:11,446: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:55:11] "POST /predict HTTP/1.1" 200 -
[2025-10-05 00:55:21,235: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:55:21] "POST /predict HTTP/1.1" 200 -
[2025-10-05 00:57:06,720: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:06] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:08,134: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:08] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:08,814: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:08] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:09,430: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:09] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:09,964: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:09] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:10,699: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:10] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:11,473: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:11] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:49,625: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-05 00:57:49,626: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-05 00:57:55,574: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:55] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:56,664: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:56] "GET / HTTP/1.1" 200 -
[2025-10-05 00:57:57,564: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:57:57] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:38,885: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:38] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:39,795: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:39] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:40,324: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:40] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:40,699: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:40] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:41,020: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:41] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:41,259: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:41] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:41,486: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:41] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:41,720: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:41] "GET / HTTP/1.1" 200 -
[2025-10-05 00:58:42,101: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:58:42] "GET / HTTP/1.1" 200 -
[2025-10-05 00:59:09,366: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-05 00:59:09,367: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-05 00:59:12,685: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:59:12] "GET / HTTP/1.1" 200 -
[2025-10-05 00:59:29,252: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 00:59:29] "POST /predict HTTP/1.1" 200 -
[2025-10-05 01:00:18,556: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 01:00:18] "GET / HTTP/1.1" 200 -
[2025-10-05 01:00:19,497: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 01:00:19] "GET / HTTP/1.1" 200 -
[2025-10-05 01:00:20,634: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 01:00:20] "GET / HTTP/1.1" 200 -
[2025-10-05 01:00:50,328: INFO: _internal]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.108.179:5000
[2025-10-05 01:00:50,329: INFO: _internal]: [33mPress CTRL+C to quit[0m
[2025-10-05 01:00:52,530: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 01:00:52] "GET / HTTP/1.1" 200 -
[2025-10-05 01:01:01,951: INFO: _internal]: 127.0.0.1 - - [05/Oct/2025 01:01:01] "POST /predict HTTP/1.1" 200 -
